version: '2.3'
services:
  pihole:
      container_name: pihole
      image: pihole/pihole:latest
      restart: unless-stopped
      ports:
          - 53:53/tcp
          - 53:53/udp
          - 67:67/udp
          - 8080:80/tcp
      environment:
          - TZ=US/New York
      volumes:
          - /home/luckierdodge/bigbox-config/etc-pihole/:/etc/pihole
          - /home/luckierdodge/bigbox-config/etc-dnsmasq.d/etc/dnsmasq.d
      cap_add:
        - NET_ADMIN
      dns:
          - 127.0.0.1
          - 1.1.1.1
  scrutiny:
    image: lscr.io/linuxserver/scrutiny
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
    volumes:
      - /home/luckierdodge/bigbox-config/scrutiny/config:/config
      - /run/udev:/run/udev:ro
    ports:
      - 8888:8080
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
      - /dev/sdg:/dev/sdg
      - /dev/sdh:/dev/sdh
      - /dev/sdi:/dev/sdi
      - /dev/sdj:/dev/sdj
    restart: unless-stopped
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=30
      - AUTOHEAL_START_PERIOD=60
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
