version: '2'
services:
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        restart: unless-stopped
        ports:
            - 10.6.0.1:53:53/tcp
            - 10.6.0.1:53:53/udp
            - 10.6.0.1:8080:80
            - 10.6.0.1:8443:443
            - 192.168.0.154:53:53/tcp
            - 192.168.0.154:53:53/udp
            - 192.168.0.154:8080:80
            - 192.168.0.154:8443:443
        environment:
            - TZ=America/Chicago
        volumes:
            - /home/luckierdodge/etc-pihole/:/etc/pihole
            - /home/luckierdodge/etc-dnsmasq.d/etc/dnsmasq.d
        dns:
            - 127.0.0.1
            - 1.1.1.1
