version: '2.1'
services:
    plex:
        container_name: plex
        image: plexinc/pms-docker
        restart: unless-stopped
        network_mode: host
        environment:
          - TZ=America/Chicago
          - PLEX_CLAIM=<https://www.plex.tv/claim>
          - ADVERTISE_IP=http://192.168.0.178:32400/
          - PLEX_UID=1000
          - PLEX_GID=1000
        hostname: ark
        volumes:
          - /home/luckierdodge/ark-config/plex/config:/config
          - /home/luckierdodge/ark-config/plex/transcode:/transcode
          - /home/luckierdodge/havoc-data/media:/data
          - /home/luckierdodge/media-storage:/media-storage
          - /var/snap/nextcloud/common/nextcloud/data/luckierdodge/files/Music:/music
          - /var/snap/nextcloud/common/nextcloud/data/luckierdodge/files/Pictures:/Pictures
    autoheal:
        container_name: autoheal
        image: willfarrell/autoheal
        restart: unless-stopped
        environment:
          - AUTOHEAL_CONTAINER_LABEL=all
          - AUTOHEAL_INTERVAL=30
          - AUTOHEAL_START_PERIOD=60
          - AUTOHEAL_DEFAULT_STOP_TIMEOUT=30
        volumes: 
          - /var/run/docker.sock:/var/run/docker.sock
    db:
        image: postgres:11-alpine
        environment:
          - POSTGRES_DB=wiki
          - POSTGRES_USER=wikijs
        env_file: secret.env
        logging:
            driver: "none"
        restart: unless-stopped
        volumes:
          - /home/luckierdodge/ark-data/postgres/data:/var/lib/postgresql/data
    wiki:
        image: requarks/wiki:2
        depends_on:
          - db
        environment:
          - DB_TYPE=postgres
          - DB_HOST=db
          - DB_PORT=5432
          - DB_USER=wikijs
          - DB_NAME=wiki
          - SSL_ACTIVE=false
        env_file: secret.env
        restart: unless-stopped
        ports:
          - "3000:3000"
        volumes:
          - /home/luckierdodge/ark-data/wikijs/data:/data
    calibre:
        image: ghcr.io/linuxserver/calibre
        container_name: calibre
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Chicago
          - GUAC_USER=luckierdodge
          - GUAC_PASS=61af3c63e8adc32cb5264b82ecfc867f #echo -n password | openssl md5
          - UMASK_SET=022
        volumes:
          - /var/snap/nextcloud/common/nextcloud/data/luckierdodge/files/Library:/Library
          - /home/luckierdodge/ark-data/calibre:/config
        ports:
          - 8080:8080
          - 8081:8081
        restart: unless-stopped
    calibre-web:
        image: ghcr.io/linuxserver/calibre-web
        container_name: calibre-web
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Chicago
          - DOCKER_MODS=linuxserver/calibre-web:calibre
        volumes:
          - /home/luckierdodge/ark-data/calibre-web:/config
          - /home/luckierdodge/ark-data/calibre:/books
        ports:
          - 8083:8083
        restart: unless-stopped
    heimdall:
        image: ghcr.io/linuxserver/heimdall
        container_name: heimdall
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Chicago
        volumes:
          - /home/luckierdodge/ark-data/heimdall:/config
        ports:
          - 11180:80
          - 11443:443
        restart: unless-stopped
