version: '2.1'
services:
    plex:
        container_name: plex
        image: plexinc/pms-docker
        restart: unless-stopped
        network_mode: host
        environment:
          - TZ=America/Chicago
          - PLEX_CLAIM=<https://www.plex.tv/claim>
          - ADVERTISE_IP=http://192.168.0.178:32400/
          - PLEX_UID=1000
          - PLEX_GID=1000
        hostname: ark
        volumes:
          - /home/luckierdodge/ark-config/plex/config:/config
          - /home/luckierdodge/ark-config/plex/transcode:/transcode
          - /home/luckierdodge/havoc-data/media:/data
    autoheal:
        container_name: autoheal
        image: willfarrell/autoheal
        restart: unless-stopped
        environment:
          - AUTOHEAL_CONTAINER_LABEL=all
          - AUTOHEAL_INTERVAL=30
          - AUTOHEAL_START_PERIOD=60
          - AUTOHEAL_DEFAULT_STOP_TIMEOUT=30
        volumes: 
          - /var/run/docker.sock:/var/run/docker.sock
    db:
        image: postgres:11-alpine
        environment:
          - POSTGRES_DB=wiki
          - POSTGRES_USER=wikijs
        env_file: secret.env
        logging:
            driver: "none"
        restart: unless-stopped
        volumes:
          - /home/luckierdodge/ark-data/postgres/data:/var/lib/postgresql/data
    wiki:
        image: requarks/wiki:2
        depends_on:
          - db
        environment:
          - DB_TYPE=postgres
          - DB_HOST=db
          - DB_PORT=5432
          - DB_USER=wikijs
          - DB_NAME=wiki
        env_file: secret.env
        restart: unless-stopped
        ports:
          - "3000:3000"
        volumes:
          - /home/luckierdodge/ark-data/wikijs/data:/data
