version: '2.1'
services:
    plex:
        container_name: plex
        image: plexinc/pms-docker
        restart: unless-stopped
        network_mode: host
        environment:
          - TZ=America/Detroit
          - PLEX_CLAIM=<https://www.plex.tv/claim>
          - ADVERTISE_IP=http://192.168.0.178:32400/
          - PLEX_UID=1000
          - PLEX_GID=1000
        hostname: ark
        volumes:
          - /home/luckierdodge/ark-config/plex/config:/config
          - /home/luckierdodge/ark-config/plex/transcode:/transcode
          - /home/luckierdodge/havoc-data/media:/data
          - /home/luckierdodge/media-storage:/media-storage
          - /var/snap/nextcloud/common/nextcloud/data/luckierdodge/files/Music:/music
          - /var/snap/nextcloud/common/nextcloud/data/luckierdodge/files/Pictures:/Pictures
    autoheal:
        container_name: autoheal
        image: willfarrell/autoheal
        restart: unless-stopped
        environment:
          - AUTOHEAL_CONTAINER_LABEL=all
          - AUTOHEAL_INTERVAL=30
          - AUTOHEAL_START_PERIOD=60
          - AUTOHEAL_DEFAULT_STOP_TIMEOUT=30
        volumes: 
          - /var/run/docker.sock:/var/run/docker.sock
    calibre:
        image: ghcr.io/linuxserver/calibre
        container_name: calibre
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Detroit
          - PASSWORD=Simple123
          - UMASK_SET=022
        volumes:
          - /var/snap/nextcloud/common/nextcloud/data/luckierdodge/files/Library:/Library
          - /home/luckierdodge/ark-data/calibre:/config
          - /home/luckierdodge/media-storage/books:/books
        ports:
          - 8080:8080
          - 8081:8081
          - 9090:9090
          - 9091:9091
        restart: unless-stopped
    calibre-web:
        image: ghcr.io/linuxserver/calibre-web
        container_name: calibre-web
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Detroit
          - DOCKER_MODS=linuxserver/calibre-web:calibre
        volumes:
          - /home/luckierdodge/ark-data/calibre-web:/config
          - /home/luckierdodge/ark-data/calibre:/books
        ports:
          - 8083:8083
        restart: unless-stopped
    heimdall:
        image: ghcr.io/linuxserver/heimdall
        container_name: heimdall
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Detroit
        volumes:
          - /home/luckierdodge/ark-data/heimdall:/config
        ports:
          - 11180:80
          - 11443:443
        restart: unless-stopped
    nextcloud:
        image: ghcr.io/linuxserver/nextcloud
        container_name: nextcloud
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Detroit
        volumes:
          - /home/luckierdodge/ark-config/nextcloud:/config
          - /home/luckierdodge/ark-data/nextcloud:/data
        ports:
          - 21443:443
        restart: unless-stopped
    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        env_file: vaultwarden.env
        volumes:
          - /home/luckierdodge/ark-data/vaultwarden:/data
        ports:
          - 28080:80
          - 23012:3012
    grocy:
        image: ghcr.io/linuxserver/grocy
        container_name: grocy
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Detroit
        volumes:
          - /home/luckierdodge/ark-config/grocy:/config
        ports:
          - 9283:80
        restart: unless-stopped
    freshrss:
        image: lscr.io/linuxserver/freshrss:latest
        container_name: freshrss
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Detroit
        volumes:
            - /home/luckierdodge/ark-config/freshrss:/config
        ports:
          - 9280:80
        restart: unless-stopped
        #    homeassistant:
        #        image: ghcr.io/linuxserver/homeassistant
        #        container_name: homeassistant
        #        network_mode: host
        #        environment:
        #            - PUID=1000
        #            - PGID=1000
        #            - TZ=US/New York
        #        volumes:
        #            - /home/luckierdodge/ark-config/homeassistant:/config
        #        ports:
        #            - 8123:8123
        #        restart: unless-stopped
    bookstack:
       image: lscr.io/linuxserver/bookstack
       container_name: bookstack
       environment:
          - PUID=1000
          - PGID=1000
          - APP_URL=https://wiki.ryandlewis.dev
          - DB_HOST=bookstack_db
          - DB_USER=bookstack
          - DB_DATABASE=bookstackapp
       env_file: secret.env
       volumes:
          - /home/luckierdodge/ark-config/bookstack:/config
       ports:
          - 6875:80
       restart: unless-stopped
       depends_on:
          - bookstack_db
    bookstack_db:
       image: lscr.io/linuxserver/mariadb
       container_name: bookstack_db
       environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Detroit
          - MYSQL_DATABASE=bookstackapp
          - MYSQL_USER=bookstack
       env_file: secret.env
       volumes:
          - /home/luckierdodge/ark-config/bookstack_db:/config
       restart: unless-stopped
    syncthing:
      image: lscr.io/linuxserver/syncthing:latest
      container_name: syncthing
      hostname: arksync #optional
      environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Detroit
      volumes:
          - /home/luckierdodge/ark-config/syncthing:/config
          - /home/luckierdodge/ark-data/syncthing/data:/data
      ports:
          - 8384:8384
          - 22000:22000/tcp
          - 22000:22000/udp
          - 21027:21027/udp
      restart: unless-stopped
