version: '2.1'
services:
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=100
            - TZ=America/Detroit
            - UMASK_SET=022
        volumes:
            - /home/luckierdodge/montecarlo-storage/config/sonarr/config:/config
            - /home/luckierdodge/havoc-data/media:/media
        ports:
          - 8989:8989
        restart: unless-stopped
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=100
            - TZ=America/Detroit
            - UMASK_SET=022
        volumes:
            - /home/luckierdodge/montecarlo-storage/config/radarr/config:/config
            - /home/luckierdodge/havoc-data/media:/media
        ports:
          - 7878:7878
        restart: unless-stopped
        #    jackett:
        #        image: linuxserver/jackett
        #        container_name: jackett
        #        environment:
        #            - PUID=1000
        #            - PGID=1000
        #            - TZ=America/Detroit
        #            - AUTO_UPDATE=true
        #        volumes:
        #            - /home/luckierdodge/montecarlo-storage/config/jackett/config:/config
        #            - /home/luckierdodge/havoc-data/jackett/downloads:/downloads
        #        network_mode: host
        #        restart: unless-stopped
        #    qbittorrent:
        #        image: linuxserver/qbittorrent
        #        container_name: qbittorrent
        #        environment:
        #            - PUID=1000
        #            - PGID=1000
        #            - TZ=America/Detroit
        #            - UMASK_SET=022
        #            - WEBUI_PORT=8080
        #        network_mode: host
        #        volumes:
        #            - /home/luckierdodge/montecarlo-storage/config/qbittorrent/config:/config
        #            - /home/luckierdodge/havoc-data/media:/media
        #        restart: "no"
    nzbget:
        image: lscr.io/linuxserver/nzbget
        container_name: nzbget
        environment:
            - PUID=1000
            - PGID=100
            - TZ=America/Detroit
        volumes:
            - /home/luckierdodge/montecarlo-storage/config/nzbget/config:/config
            - /home/luckierdodge/havoc-data/media:/media #optional
        ports:
            - 6789:6789
        restart: "no"
    autoheal:
        container_name: autoheal
        image: willfarrell/autoheal
        restart: unless-stopped
        network_mode: host
        environment:
            - AUTOHEAL_CONTAINER_LABEL=all
            - AUTOHEAL_INTERVAL=30
            - AUTOHEAL_START_PERIOD=60
            - AUTOHEAL_DEFAULT_STOP_TIMEOUT=30
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
    ombi:
        image: ghcr.io/linuxserver/ombi
        container_name: ombi
        ports:
            - 3579:3579
        environment:
            - PUID=1000
            - PGID=100
            - TZ=America/Detroit
        volumes:
            - /home/luckierdodge/montecarlo-storage/config/ombi:/config
        restart: unless-stopped

