version: '2.1'
services:
    plex:
        container_name: plex
        image: plexinc/pms-docker
        restart: unless-stopped
        network_mode: host
        environment:
          - TZ=America/Chicago
          - PLEX_CLAIM=<https://www.plex.tv/claim>
          - ADVERTISE_IP=http://192.168.0.117:32400/
          - PLEX_UID=1000
          - PLEX_GID=1000
        hostname: havoc
        volumes:
          - /home/luckierdodge/havoc-data/plex/config:/config
          - /home/luckierdodge/havoc-data/plex/transcode:/transcode
          - /home/luckierdodge/havoc-data/media:/data
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - UMASK_SET=022
        volumes:
            - /home/luckierdodge/havoc-data/sonarr/config:/config
            - /home/luckierdodge/havoc-data/media:/media
        network_mode: host
        restart: unless-stopped
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - UMASK_SET=022
        volumes:
            - /home/luckierdodge/havoc-data/radarr/config:/config
            - /home/luckierdodge/havoc-data/media:/media
        network_mode: host
        restart: unless-stopped
    jackett:
        image: linuxserver/jackett
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - AUTO_UPDATE=true
        volumes:
            - /home/luckierdodge/havoc-data/jackett/config:/config
            - /home/luckierdodge/havoc-data/jackett/downloads:/downloads
        network_mode: host
        restart: unless-stopped
    qbittorrent:
        image: linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - UMASK_SET=022
            - WEBUI_PORT=8080
        network_mode: host
        volumes:
            - /home/luckierdodge/havoc-data/qbittorrent/config:/config
            - /home/luckierdodge/havoc-data/media:/media
        restart: unless-stopped
