version: '2.1'
services:
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - UMASK_SET=022
        volumes:
            - /home/luckierdodge/havoc-config/sonarr/config:/config
            - /home/luckierdodge/havoc-data/media:/media
        network_mode: host
        restart: unless-stopped
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - UMASK_SET=022
        volumes:
            - /home/luckierdodge/havoc-config/radarr/config:/config
            - /home/luckierdodge/havoc-data/media:/media
        network_mode: host
        restart: unless-stopped
    jackett:
        image: linuxserver/jackett
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - AUTO_UPDATE=true
        volumes:
            - /home/luckierdodge/havoc-config/jackett/config:/config
            - /home/luckierdodge/havoc-data/jackett/downloads:/downloads
        network_mode: host
        restart: unless-stopped
    qbittorrent:
        image: linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - UMASK_SET=022
            - WEBUI_PORT=8080
        network_mode: host
        volumes:
            - /home/luckierdodge/havoc-config/qbittorrent/config:/config
            - /home/luckierdodge/havoc-data/media:/media
        restart: unless-stopped
    autoheal:
        container_name: autoheal
        image: willfarrell/autoheal
        restart: unless-stopped
        network_mode: host
        environment:
            - AUTOHEAL_CONTAINER_LABEL=all
            - AUTOHEAL_INTERVAL=30
            - AUTOHEAL_START_PERIOD=60
            - AUTOHEAL_DEFAULT_STOP_TIMEOUT=30
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
    ombi:
        image: ghcr.io/linuxserver/ombi
        container_name: ombi
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - /home/luckierdodge/havoc-config/ombi
        restart: unless-stopped

