services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400
    environment:
      - TZ=America/Chicago
      - PLEX_CLAIM=<https://www.plex.tv/claim>
      - ADVERTISE_IP=https://plex.ryandlewis.dev/
      - PLEX_UID=1000
      - PLEX_GID=100
    hostname: killingtime
    volumes:
      - /home/luckierdodge/killingtime-storage/config/plex/config:/config
      - /home/luckierdodge/killingtime-storage/config/plex/transcode:/transcode
      - /home/luckierdodge/havoc-data/media:/data
      - /home/luckierdodge/media-storage:/media-storage
      - /home/luckierdodge/killingtime-storage/data/nextcloud/luckierdodge/files/Music:/music
      - /home/luckierdodge/killingtime-storage/data/nextcloud/luckierdodge/files/Pictures:/Pictures
    labels:
      - docker-volume-backup.stop-during-backup=true
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on: ["gluetun"]
    network_mode: service:gluetun
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - UMASK_SET=022
    volumes:
      - /home/luckierdodge/killingtime-storage/config/sonarr/config:/config
      - /home/luckierdodge/havoc-data/media:/media
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on: ["gluetun"]
    network_mode: service:gluetun
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - UMASK_SET=022
    volumes:
      - /home/luckierdodge/killingtime-storage/config/radarr/config:/config
      - /home/luckierdodge/havoc-data/media:/media
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    depends_on: ["gluetun"]
    network_mode: service:gluetun
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /home/luckierdodge/killingtime-storage/config/lidarr/config:/config
      - /home/luckierdodge/havoc-data/media:/media
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true
  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    depends_on: ["gluetun"]
    network_mode: service:gluetun
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /home/luckierdodge/killingtime-storage/config/nzbget/config:/config
      - /home/luckierdodge/havoc-data/media:/media #optional
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /home/luckierdodge/killingtime-storage/config/ombi:/config
    depends_on: ["gluetun"]
    network_mode: service:gluetun
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - JELLYFIN_PublishedServerUrl=jellyfin.ryandlewis.dev #optional
    volumes:
      - /home/luckierdodge/killingtime-storage/config/jellyfin:/config
      - /home/luckierdodge/havoc-data/media/tv:/data/tvshows
      - /home/luckierdodge/havoc-data/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    env_file: ./gluetun.env
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      #- 9117:9117 # Jackett
      - 7070:7070 # QBittorrent
      - 9696:9696 # Prowlarr
      - 6881:6881 # QBittorrent Incoming Port
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 8686:8686 # Lidarr
      - 6789:6789 # Nzbget
      - 3579:3579 # Ombi
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - SERVER_COUNTRIES=United States
      - PORT_FORWARD_ONLY=on
  #jackett:
  #  image: linuxserver/jackett
  #  container_name: jackett
  #  depends_on: ["gluetun"]
  #  network_mode: service:gluetun
  #  sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
  #  restart: no
  #  environment:
  #    - PUID=1000
  #    - PGID=100
  #    - TZ=America/Chicago
  #    - AUTO_UPDATE=true
  #  volumes:
  #    - /etc/localtime:/etc/localtime:ro
  #    - /home/luckierdodge/killingtime-storage/config/jackett/config:/config:z
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on: ["gluetun"]
    network_mode: service:gluetun
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /home/luckierdodge/killingtime-storage/config/prowlarr/config:/config
    labels:
      - docker-volume-backup.stop-during-backup=true
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    depends_on: ["gluetun"]
    network_mode: service:gluetun
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - WEBUI_PORT=7070
      - TORRENTING_PORT=6881
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/luckierdodge/killingtime-storage/config/qbittorrent/config:/config:z
      - /home/luckierdodge/havoc-data/media/downloads:/media/downloads:z
      - /home/luckierdodge/havoc-data/media/movies:/media/movies:z
      - /home/luckierdodge/havoc-data/media/tv:/media/tv:z
      - /home/luckierdodge/havoc-data/media/music:/media/music:z
    labels:
      - docker-volume-backup.stop-during-backup=true
