services:
  paperless_broker:
    container_name: paperless_broker
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /home/luckierdodge/killingtime-storage/data/paperless/paperless_brokerdata:/data
    labels:
      - docker-volume-backup.stop-during-backup=true
  paperless_db:
    container_name: paperless_db
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - /home/luckierdodge/killingtime-storage/data/paperless/paperless_pgdata:/var/lib/postgresql/data
    env_file: paperless_db.env
    labels:
      - docker-volume-backup.stop-during-backup=true
  paperless_webserver:
    container_name: paperless_webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperless_db
      - paperless_broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/luckierdodge/killingtime-storage/data/paperless/paperless_data:/usr/src/paperless/data
      - /home/luckierdodge/killingtime-storage/data/paperless/paperless_media:/usr/src/paperless/media
      - /home/luckierdodge/killingtime-storage/data/paperless/paperless_export:/usr/src/paperless/export
      - /home/luckierdodge/killingtime-storage/data/paperless/paperless_consume:/usr/src/paperless/consume
    env_file: paperless_webserver.env
    environment:
      PAPERLESS_REDIS: redis://paperless_broker:6379
      PAPERLESS_DBHOST: paperless_db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    labels:
      - docker-volume-backup.stop-during-backup=true
  gotenberg:
    container_name: gotenberg
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  tika:
    container_name: tika
    image: docker.io/apache/tika:latest
    restart: unless-stopped
